# Generated by Django 4.1.1 on 2022-09-20 07:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Copyright',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoryofwork', models.CharField(max_length=100)),
                ('clientname', models.CharField(max_length=100)),
                ('titleofwork', models.CharField(max_length=1000)),
                ('modeofcontact', models.EmailField(max_length=100)),
                ('referedby', models.CharField(max_length=1000)),
                ('conntactnumber', models.IntegerField(max_length=10)),
                ('emailid', models.EmailField(max_length=100)),
                ('uid', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Copyrightstatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uid', models.CharField(max_length=20)),
                ('quotationstatus', models.CharField(max_length=20)),
                ('quotedamount', models.CharField(max_length=20)),
                ('toassignteam', models.CharField(max_length=20)),
                ('projectduedate', models.CharField(max_length=20)),
                ('copyrightcompleted', models.BooleanField(max_length=20)),
            ],
        ),
    ]
