# Generated by Django 4.0.4 on 2022-09-07 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patent', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patentapplication',
            name='modeofcontact',
            field=models.CharField(max_length=50),
        ),
    ]
