# Generated by Django 4.0.4 on 2022-09-07 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Trademark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20)),
                ('organisation', models.CharField(max_length=30)),
                ('resource', models.IntegerField()),
                ('modeofcontact', models.EmailField(max_length=50)),
                ('referedby', models.IntegerField()),
                ('conntactnumber', models.CharField(max_length=10)),
                ('emailid', models.EmailField(max_length=50)),
                ('uid', models.CharField(max_length=20)),
            ],
        ),
    ]
